// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.db1.prisma",
  migrations: {
    path: "prisma/migrations-db1",
  },
  datasource: {
    url: process.env["DATABASE_URL_DB1"],
  },
});
